package com.triviola.agentic.workflow;
public enum EventType {
    WORKFLOW_CREATED, WORKFLOW_STARTED, WORKFLOW_COMPLETED,
    TASK_STARTED, TASK_PASSED, TASK_FAILED, RETRY_SCHEDULED,
    APPROVAL_REQUIRED, TASK_APPROVED, TASK_REJECTED,
    DECISION_RECORDED, REPLAN_REQUESTED, ROLLBACK_COMPLETED, SAFE_STOPPED
}
